[project]
name = "librarian"
version = "0.1.0"
description = "A LangGraph-powered backend web server for AI agent workflows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph",
    "langchain",
    "langchain-openai",
    "python-dotenv"
]
